cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'ripgrep'
brew 'tmux'
brew 'vim'

cask 'alfred'
cask 'google-chrome'
cask 'iterm2'
cask 'karabiner-elements'
cask 'slack'
cask 'tower'
