cask_args appdir: '/Applications'

brew 'zsh'

tap 'homebrew/bundle'

tap 'neovim/neovim'
brew 'neovim'

cask 'font-meslo-lg'

cask 'atom'
cask 'flux'
cask 'google-chrome'
cask 'iterm2'
cask 'slack'

