cask_args appdir: '/Applications'

tap 'homebrew/bundle'

tap 'neovim/neovim'
brew 'neovim'

tap 'caskroom/homebrew-fonts'
cask 'font-meslo-lg'

tap 'caskroom/versions'
cask 'alfred2'

cask 'flux'
cask 'google-chrome'
cask 'iterm2'
cask 'slack'
cask 'visual-studio-code'
