#!/usr/bin/env bash

brew bundle

open "${HOME}/.dotfiles/macos/iterm2/seoul256.itermcolors"
open "${HOME}/.dotfiles/macos/iterm2/seoul256-light.itermcolors"
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
defaults write com.googlecode.iterm2 PromptOnQuit -bool false
